### ISSUE TITLE
Issues comparing models with phylo_path

### ISSUE THREAD

**Issue by Madeleinecg** [Ax3man/phylopath#22]
Hi,

I'm using the phylo_path function to compare models (using the logistic_IG10 method). I'm getting errors saying that it can't fit a model with two particular variables in it, but I've checked and checked again and there are no models in the set that contain both these variables together, even via indirect links. I think I must have misunderstood what phylo_path is doing - I thought it was running each model independently, but is each model also using the other models in the set?

Many thanks

**Comment by Ax3man** [comment]
The `phylo_path` function does model comparison using the d-separation method. Instead of fitting the paths described in your models, it instead checks whether variables that should be (conditionally) independent are indeed so. I think the book chapter by Alejandro and Achaz explains this quite clearly and in more detail: http://www.consevol.org/pdf/Books/Chapter%208%20Modern%20Phylogenetic%20Comparative%20Methods%20book.pdf

**Comment by Ax3man** [comment]
I'm going to close this issue now, but do let me know if you have further trouble.
